### ISSUE TITLE
Need to fix image duplication issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#254] opened 2020-07-28 12:36 UTC
We need to images duplication issue. Event banner will automatically duplicate in backed.

**Comment by krinaydhanani** [comment] 2020-12-02 07:31
I try to find out the duplication issue much time but I can not reproduce it. If I found in future anything regarding duplication I will open the issue with proper stapes.

**Comment by tamanna-ahuja** [comment] 2022-03-22 10:41
Would request you to close this issue if we are not able to reproduce now

**Comment by mistry-jignesh** [comment] 2022-03-24 06:59
I have verified issue . 

Now this issue working fine. Image banner not duplicate in the media folder.

So I closed the issue.

**Closed by mistry-jignesh** 2022-03-24 06:59 UTC
Labels: Issue Resolved
