### ISSUE TITLE
Event sort issue with date time after plugin update

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#587] opened 2020-10-13 06:42 UTC
Event sort issue with date time after plugin update

**Comment by wpem-kishan** [comment] 2020-10-13 06:43
```
add_action('init', 'change_date_formate');
function change_date_formate()
{
	if(get_option('wpem_hange_date_formate'))
		return;

	$args = [
		'post_type' => 'event_listing',
		'posts_per_page' => -1,
		'order_by' => 'ID',
		'order' => 'DESC',
	];
	$events = new WP_Query( $args );

	if( !empty($events) && $events->found_posts > 0 )	
	{
		//get date and time setting defined in admin panel Event listing -> Settings -> Date & Time formatting
		$datepicker_date_format 	= WP_Event_Manager_Date_Time::get_datepicker_format();
		
		//covert datepicker format  into php date() function date format
		$php_date_format 		= WP_Event_Manager_Date_Time::get_view_date_format_from_datepicker_date_format( $datepicker_date_format );

		foreach($events->posts as $event)
		{
			$event_start_date = $event->_event_start_date;
			$event_start_time = $event->_event_start_time;

			if(strpos($event_start_date, ':00') !== false)
			{
				$start_date =  $event_start_date;
			}
			else
			{
				$start_date =  $event_start_date.' '.$event_start_time. ':00' ;	
			}

			//Convert date and time value into DB formatted format and save eg. 1970-01-01 00:00:00
			$start_date_dbformatted = WP_Event_Manager_Date_Time::date_parse_from_format($php_date_format . ' H:i:s'  , $start_date);
			$start_date_dbformatted = !empty($start_date_dbformatted) ? $start_date_dbformatted : $start_date;

			update_post_meta( $event->ID, '_event_start_date', $start_date_dbformatted );



			$event_end_date = $event->_event_end_date;
			$event_end_time = $event->_event_end_time;
			
			if(strpos($event_end_date, ':00') !== false)
			{
				$end_date =  $event_end_date;
			}
			else
			{
				$end_date =  $event_end_date.' '.$event_end_time. ':00' ;	
			}

			//Convert date and time value into DB formatted format and save eg. 1970-01-01 00:00:00
			$end_date_dbformatted = WP_Event_Manager_Date_Time::date_parse_from_format($php_date_format . ' H:i:s'  , $end_date);
			$end_date_dbformatted = !empty($end_date_dbformatted) ? $end_date_dbformatted : $end_date;

			update_post_meta( $event->ID, '_event_end_date', $end_date_dbformatted );
		}

		update_option('wpem_hange_date_formate', '1');
	}
}
```

**Comment by rollsappletree** [comment] 2020-10-21 11:08
I have a issue that seems really similar to this one. Even in the event manager backend "list events" page, if I order by "event start date", the ordering is not correct.
Ovviously the problem is propagated in the shortcut "past_events" too. So I cant use this feature that is really important for me.

I also tried to apply your patch, but it seems not working: in fact all my event's start date became "today" instead of fixing the problem.

Cheers,
C

**Comment by Priya-Goenka** [comment] 2020-11-30 12:31
@krinay please review what the customer is saying and let me know, what is this exactly for?

**Comment by krinaydhanani** [comment] 2020-12-02 07:44
@Priya-Goenka The original issue was totally different and @rollsappletree issue was fixed in the latest version.

**Comment by rollsappletree** [comment] 2020-12-02 08:13
Hi, a question: 
when was it released the latest version? 'cause i had this problem just a month ago or so... 

Thanks in advance,
C

**Comment by Priya-Goenka** [comment] 2020-12-03 10:47
Hi, We had released the latest plugin last night. (2nd Deecember)

**Closed** 2020-12-03 10:47 UTC
Labels: Bug, Documentation, Enhancement
