### ISSUE TITLE
Category selection box issue in mobile view

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#315] opened 2020-08-12 05:04 UTC
#4470 Several bugs and suggestions

I had checked from my end found this issue in category and type both field.

![89862174-052b8580-dbc5-11ea-95a9-14571e225b29](https://user-images.githubusercontent.com/25837982/89977864-d88d7180-dc89-11ea-959a-e4e3a509d7e5.jpeg)

**Comment by hiteshmakvana** [comment] 2020-08-12 05:06
Duplicate of #186

**Comment by mistry-jignesh** [comment] 2022-03-22 09:00
This issue is duplicated with #186. 

So I closed the issue.

**Closed by mistry-jignesh** 2022-03-22 09:00 UTC
Labels: Bug
